### ISSUE TITLE
lis_esolver_get_evectors outputs CSR matrix but explained as COO in guide

### ISSUE THREAD

**Issue by occar421** [anishida/lis#12]
In the function `lis_esolver_get_evectors` the output matrix `M` is assembled as CSR, according to https://github.com/anishida/lis/blob/develop/src/esolver/lis_esolver.c#L1136

However, user's guide says that is by COO format.
https://github.com/anishida/lis/blob/master/doc/lis-ug-en.tex#L6887
https://github.com/anishida/lis/blob/master/doc/lis-ug-ja.tex#L6723 (preview not available)

**Comment by anishida** [comment]
Hi,

Thank you for your notice.
We fixed the file format to COO and released a new version.
Please enjoy!

Sincerely,
Akira Nishida
