### ISSUE TITLE
debian package

### ISSUE THREAD

**Issue by alexmyczko** [anishida/lis#13]
Hi

someone was asking for a debian package of your software: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854324

so here's an almost ready package:
http://sid.ethz.ch/debian/lis/

**Comment by anishida** [comment]
Hi,

Thank you for your notice!
Although I am not familiar with Debian, please tell me
if you need anything.

Sincerely,
Akira Nishida

**Comment by anishida** [comment]
Hi,

As for the Fedora package, I found the following settings
by Florian at https://kojipkgs.fedoraproject.org//packages/lis/2.0.7/1.fc28/data/logs/x86_64/build.log:

  Build with OpenMP library                  = no
configure: WARNING: unrecognized options: --disable-rpath
  Build with MPI library                     = no
  Enable FORTRAN 77 compatible interface     = no
  Enable Fortran 90 compatible interface     = no
  Enable SA-AMG preconditioner               = yes
  Enable double-double precision support     = yes
  Enable SSE2                                = yes
  Enable FMA                                 = no
  Enable long double precision support       = no
  Enable 64bit integer support               = no
  Enable complex scalar support              = no
  Enable dynamic linking                     = yes
  Enable profiling                           = no
  C compiler        = gcc
  C flags           = -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection -DHAVE_CONFIG_H -msse2 
  C libraries       = -lm  
  F90 compiler      = f95
  F90 flags         = -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection -I/usr/lib64/gfortran/modules -Wp,-DZERO_ORIGIN=1
  F90 libraries     =

I hope this will be of help to you.
Please send us any questions and comments.

Sincerely,
Akira Nishida

-----Original Message-----
From: Akira NISHIDA [mailto:dolce@yo.rim.or.jp] 
Sent: Saturday, March 3, 2018 9:58 AM
To: 'anishida/lis' <reply@reply.github.com>; 'anishida/lis' <lis@noreply.github.com>
Cc: 'Subscribed' <subscribed@noreply.github.com>
Subject: RE: [anishida/lis] debian package (#13)

Hi,

Thank you for your notice!
Although I am not familiar with Debian, please tell me if you need anything.

Sincerely,
Akira Nishida
