### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Konstantin8105** [anishida/lis#15]
Could you clarify?
Have you research performance depending to input sparse format.

**Comment by anishida** [comment]
Hi,

> Could you clarify?
> Have you research performance depending to input sparse format.

Yes.
We appreciate it if you could check the following:

Hisashi Kotakemori, Hidehiko Hasegawa, Tamito Kajiyama, Akira Nukada, Reiji Suda, and Akira Nishida (2008). Performance Evaluation of Parallel Sparse Matrix-Vector Products on SGI Altix3700. OpenMP Shared Memory Parallel Programming. Lecture Notes in Computer Science 4315. Springer. pp. 153-163. doi:10.1007/978-3-540-68555-5_13. ISBN 3-540-68554-5.

Hisashi Kotakemori, Hidehiko Hasegawa, and Akira Nishida (2005). Performance Evaluation of a Parallel Iterative Method Library using OpenMP. Proceedings of the 8th International Conference on High Performance Computing in Asia Pacific Region (HPC Asia 2005). Beijing. IEEE. pp. 432-436. doi:10.1109/HPCASIA.2005.74. ISBN 0-7695-2486-9.

Sincerely,
Akira Nishida
