### ISSUE TITLE
Proposal: init vector

### ISSUE THREAD

**Issue by Konstantin8105** [anishida/lis#21]
Hello, @anishida ,
In according to documentation , we have only 2 chose initial vector - init be 0 and be 1.
May I initialize vector for solving "Ax=b" values from file ?

Konstantin

**Comment by Konstantin8105** [comment]
Generally, I mean add that option in program 'lsolve'.

**Comment by anishida** [comment]
Hi,

Thank you for your question.
Currently, we do not have an option to assign the initial values of x.

Sincerely,
Akira Nishida

**Comment by anishida** [comment]
Hi,

However, of cource you can use a predefined x with lis_solve() 
in your own programs.

Sincerely,
Akira Nishida

-----Original Message-----
From: Akira NISHIDA [mailto:dolce@yo.rim.or.jp] On Behalf Of nishida@kyudai.jp
Sent: Saturday, September 29, 2018 12:19 AM
To: 'anishida/lis' <reply@reply.github.com>; 'anishida/lis' <lis@noreply.github.com>
Cc: 'Akira Nishida' <nishida@ssisc.org>; 'Mention' <mention@noreply.github.com>
Subject: RE: [anishida/lis] Proposal: init vector (#21)

Hi,

Thank you for your question.
Currently, we do not have an option to assign the initial values of x.

Sincerely,
Akira Nishida

**Comment by OliverEvans96** [comment]
@Konstantin8105 - as anishida said, you can read your initial x from a file and then assign it to the lis vector using [`lis_vector_set_value`](https://github.com/anishida/lis/blob/92dc779412095945079478baf8ffec6701d6a4f3/doc/lis-ug-en.tex#L4313). Then, be sure to set the solver option [`-initx_zeros false`](https://github.com/anishida/lis/blob/92dc779412095945079478baf8ffec6701d6a4f3/doc/lis-ug-en.tex#L2057)

Oliver
