### ISSUE TITLE
netlib page out of date

### ISSUE THREAD

**Issue by OliverEvans96** [anishida/lis#24]
Hi anishida,

I noticed that the [netlib page](http://www.netlib.org/misc/lis/) is five years out of date, on version 1.3.33. I wonder if it could be easily updated. When I google "lis iterative solver", the netlib page is shown far before the github page. Also, when googling "lis iterative solver manual", the first result is the out-of-date pdf on the netlib page.

Thanks,
Oliver

**Comment by anishida** [comment]
Hi,

Thank you for your question.
The page at Netlib can be updated by sending our new files to Prof. Dongarra, 
but it will not be realistic because we update very frequently.
Instead, you can go to our site by just clicking the link on the top of the page.

Sincerely,
Akira Nishida
