### ISSUE TITLE
OpenMP needs care on macOS with Apple clang

### ISSUE THREAD

**Issue by Fabian188** [anishida/lis#26]
I have Catalina 10.15.7 with system clang (Apple clang version 12.0.0 (clang-1200.0.32.21))
standard configure --enable-omp finds no OpenMP.

It works in two ways:

With Apple's system clang
`./configure --enable-omp CFLAGS="-Xclang -fopenmp" LDFLAGS="-lomp"`

or with the brew clang
`./configure CC=/usr/local/opt/llvm/bin/clang --enable-omp LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"`

I suggest to add the first variant in the apple default configuration.

**Comment by anishida** [comment]
Hi,

Thank you for your suggestion. I made a clang version lis-2.0.24-clang01.zip and uploaded it. Ths URL is as follows:

https://www.ssisc.org/lis/dl/lis-2.0.24-clang01.zip. 

If $ax_cv_c_compiler_vendor is "clang", the configure sets OMPFLAG and LDFLAGS as follows:

OMPFLAG="-Xclang -fopenmp" LDFLAGS="$LDFLAGS -lomp -L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib" ;;

I appreciate it if you could check if the new configure works with both the system clang and brew clang. If you need a fix, you can make a new configure file by editing configure.ac and running reconfigure.sh. If it works, I would like to reflect it to the next version. Thank you in advance for your cooperation.

Sincerely,
Akira Nishida

**Comment by anishida** [comment]
Fabian,

I missed your request to add only the first content. I uploaded the updated library to https://www.ssisc.org/lis/dl/lis-2.0.24-clang02.zip. 

Sincerely,
Akira Nishida

-----Original Message-----
From: Akira NISHIDA 
Sent: Tuesday, November 17, 2020 3:14 AM
To: 'anishida/lis' <reply@reply.github.com>; 'anishida/lis' <lis@noreply.github.com>
Cc: 'Subscribed' <subscribed@noreply.github.com>
Subject: RE: [anishida/lis] OpenMP needs care on macOS with Apple clang (#26)

Hi,

Thank you for your suggestion. I made a clang version lis-2.0.24-clang01.zip and uploaded it. Ths URL is as follows:

https://www.ssisc.org/lis/dl/lis-2.0.24-clang01.zip. 

If $ax_cv_c_compiler_vendor is "clang", the configure sets OMPFLAG and LDFLAGS as follows:

OMPFLAG="-Xclang -fopenmp" LDFLAGS="$LDFLAGS -lomp -L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib" ;;

I appreciate it if you could check if the new configure works with both the system clang and brew clang. If you need a fix, you can make a new configure file by editing configure.ac and running reconfigure.sh. If it works, I would like to reflect it to the next version. Thank you in advance for your cooperation.

Sincerely,
Akira Nishida

**Comment by Fabian188** [comment]
Akira, unfortunately it does not work. 

```
case $ax_cv_c_compiler_vendor in
        clang) OMPFLAG="-Xclang -fopenmp" LDFLAGS="$LDFLAGS -lomp" ;;
```

Has no effect at all. Please note, that the issue only applies to Apple's clang and not for other system's clang. Also Apple's clang behaves much like gnu gcc, e.g. it can be called via gcc.

```
grep vendor config.log
configure:4875: checking for C compiler vendor
configure:5753: checking for Fortran compiler vendor
ax_cv_c_compiler_vendor=gnu
ax_cv_f77_compiler_vendor=gnu
build_vendor='apple'
host_vendor='apple'
target_vendor='apple'
```

I provide my config.log. I had to learn that also --enable-saamg is necessary, otherwise there is an error with the tests (the library itself works).
[config.log](https://github.com/anishida/lis/files/5550209/config.log)

**Comment by anishida** [comment]
Fabian,

Thank you for your comment. I updated the configure file and uploaded https://www.ssisc.org/lis/dl/lis-2.0.24-clang03.zip. If you do not specify --enable-32bit, it now sets "-m64" without specifying --enable-saamg.  

Sincerely,
Akira Nishida

**Comment by Fabian188** [comment]
Akira, 

the clang03 version works out of the box: `configure --enable-omp` worked smoothly!

However, one cannot give alternative compilers any more. The CC option is ignored.
`configure --enable-omp CC=/usr/local/bin/gcc-10` worked with the original 2.0.24. I admit that identifying Apple's clang
might not be easy, at it trys to mimic gcc (and also listens to the call gcc). 

I add the config.log for the original 2.0.24 using gcc-10 installed by brew.
[config_gcc10.log](https://github.com/anishida/lis/files/5556348/config_gcc10.log)

**Comment by anishida** [comment]
Fabian,

Thank you for your comment. I slightly modified the file and uploaded https://www.ssisc.org/lis/dl/lis-2.0.24-clang04.zip. I appreciate it if you could check it.

Sincerely,
Akira Nishida

**Comment by Fabian188** [comment]
Akira,

it still works in the default configuration with clang and CC is also recognized.

Hover it now fails with 
`configure --enable-omp CC=/usr/local/bin/gcc-10 `
by
```
checking for a library suffix to use... checking whether the C compiler works... no
configure: error: in `/Users/fwein/Downloads/t/lis-2.0.24':
configure: error: C compiler cannot create executables
See `config.log' for more details
```
which is caused by
```
configure:4043: checking whether the C compiler works
configure:4065: /usr/local/bin/gcc-10  -m64   -lomp conftest.c  >&5
ld: library not found for -lomp
collect2: error: ld returned 1 exit status
configure:4069: $? = 1
```
And the cure is simply
`configure --enable-omp CC=/usr/local/bin/gcc-10 LDFLAGS="-L/usr/local/lib"`

In my eyes this is almost fine. It works with the default configuration, it recognized CC and when using CC one need to provide what is requested. But I believe gcc-10 doesn't need libomp as it has it's own stuff?!

Honestly I'm confused why -L/usr/local/lib is sometimes required and sometimes not (I had similar behaviour in other configurations).  I just checked that funny enough Apple's clang does not come with OpenMP but supports OpenMP. It needs libomp to be provided manually (e.g. by brew) which is installed almost a million times a year:  https://formulae.brew.sh/formula/libomp

I guess any serious developer on Mac has it installed already and a hint in the documentation might not be necessary. 

I suggest either to remove -lomp when CC is provided or leave it as it is. Honestly I fail to understand the current logic in configure.ac, so cannot provide any input there.

Thank you very much for providing lis! It is the best linear solver we know of for large scale 3D FEM problems and I looking forward to experiment with the eigenvalue solvers of lis.

**Comment by anishida** [comment]
Fabian,

I uploaded lis-2.0.24-clang05.zip. It now checks if '$CC --version | grep clang' is true or not.

Sincerely,
Akira Nishida

**Comment by Fabian188** [comment]
This works for both
`./configure --enable-omp`
using Apple's native clang by its name gcc.

Also 
`/configure --enable-omp CC=gcc-10`
works nicely.

Thank you very much!
