### ISSUE TITLE
CC=foo option overridden in configure.ac

### ISSUE THREAD

**Issue by carlodefalco** [anishida/lis#28]
Hi,

I am trying to compile lis-2.0.28 on macos 11.1 with XCode 12
I am running configure with the following options

    ../configure \
    MPICC=mpicc-openmpi-mp F77=mpif90-openmpi-mp FC=mpif90-openmpi-mp MPIF77=mpif90-openmpi-mp \
    MPIRUN=mpirun-openmpi-mp CC=mpicc-openmpi-mp CFLAGS="-m64 " CPP=/usr/bin/cpp \
    LDFLAGS="-L/opt/local/lib" \
    CPPFLAGS="-I/opt/local/include" \
    --enable-shared \
    --disable-complex \
    --enable-mpi \
    --prefix=/opt/lis/2.0.28

mpicc is installed via macports so it has a non standard name
the value of CC=mpicc-openmpi-mp is ignored because configure forces CC to be mpicc here : 

    https://github.com/anishida/lis/blob/master/configure.ac#L928

it would be probably more robust to add -m64 to CFLAGS rather than CC ...

**Comment by anishida** [comment]
Hi,

Thank you for your notice. I uploaded a new version of configure to the develop branch on github. I appreciate it if you could try it.

Sincerely,
Akira Nishida

**Comment by carlodefalco** [comment]
Thanks for the VERY quick fix! 
That is working for me.

Carlo de Falco

**Comment by anishida** [comment]
Carlo,

I updated the configure script, where I deleted the MPI configurations for MacOS, because CC and FC are set to $MPICC and $MPIFC respectively by default. Please tell me if it does not work. 

Sincerely,
Akira Nishida
