### ISSUE TITLE
Missing initialisation of `nr`

### ISSUE THREAD

**Issue by TLCFEM** [anishida/lis#36]
https://github.com/anishida/lis/blob/a116bfacf5c778e1374181e679f656059cd939ed/src/matrix/lis_matrix_bsr.c#L1079

In this function, I think `nr` shall be initialised `nr=A->nr`, comparing with other similar functions?

**Comment by anishida** [comment]
Thank you for your pointing out.
We fixed the bugs and released a new version.

Sincerely,
Akira Nishida

From: Theodore ***@***.*** 
Sent: Wednesday, June 14, 2023 4:50 AM
To: anishida/lis ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [anishida/lis] Missing initialisation of `nr` (Issue #36)

https://github.com/anishida/lis/blob/a116bfacf5c778e1374181e679f656059cd939ed/src/matrix/lis_matrix_bsr.c#L1079
In this function, I think nr shall be initialised nr=A->nr, comparing with other similar functions?
