### ISSUE TITLE
autoreconf

### ISSUE THREAD

**Issue by florianl** [anishida/lis#7]
Hi!

There are several error while running autoreconf:

configure.ac:1115: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2661: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2678: AC_LINK_IFELSE is expanded from...
m4/libtool.m4:1022: _LT_SYS_MODULE_PATH_AIX is expanded from...
m4/libtool.m4:4158: _LT_LINKER_SHLIBS is expanded from...
m4/libtool.m4:5233: _LT_LANG_C_CONFIG is expanded from...
m4/libtool.m4:138: _LT_SETUP is expanded from...
m4/libtool.m4:67: LT_INIT is expanded from...
m4/libtool.m4:102: AC_PROG_LIBTOOL is expanded from...
configure.ac:1115: the top level
configure.ac:1115: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2661: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2678: AC_LINK_IFELSE is expanded from...
m4/libtool.m4:4158: _LT_LINKER_SHLIBS is expanded from...
m4/libtool.m4:5233: _LT_LANG_C_CONFIG is expanded from...
m4/libtool.m4:138: _LT_SETUP is expanded from...
m4/libtool.m4:67: LT_INIT is expanded from...
m4/libtool.m4:102: AC_PROG_LIBTOOL is expanded from...
configure.ac:1115: the top level
configure.ac:1115: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2661: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2678: AC_LINK_IFELSE is expanded from...
m4/libtool.m4:1022: _LT_SYS_MODULE_PATH_AIX is expanded from...
m4/libtool.m4:4158: _LT_LINKER_SHLIBS is expanded from...
m4/libtool.m4:5233: _LT_LANG_C_CONFIG is expanded from...
m4/libtool.m4:138: _LT_SETUP is expanded from...
m4/libtool.m4:67: LT_INIT is expanded from...
m4/libtool.m4:102: AC_PROG_LIBTOOL is expanded from...
configure.ac:1115: the top level
configure.ac:1115: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2661: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2678: AC_LINK_IFELSE is expanded from...
m4/libtool.m4:4158: _LT_LINKER_SHLIBS is expanded from...
m4/libtool.m4:5233: _LT_LANG_C_CONFIG is expanded from...
m4/libtool.m4:138: _LT_SETUP is expanded from...
m4/libtool.m4:67: LT_INIT is expanded from...
m4/libtool.m4:102: AC_PROG_LIBTOOL is expanded from...
configure.ac:1115: the top level
configure.ac:1115: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2661: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2678: AC_LINK_IFELSE is expanded from...
m4/libtool.m4:1022: _LT_SYS_MODULE_PATH_AIX is expanded from...
m4/libtool.m4:4158: _LT_LINKER_SHLIBS is expanded from...
m4/libtool.m4:5233: _LT_LANG_C_CONFIG is expanded from...
m4/libtool.m4:138: _LT_SETUP is expanded from...
m4/libtool.m4:67: LT_INIT is expanded from...
m4/libtool.m4:102: AC_PROG_LIBTOOL is expanded from...
configure.ac:1115: the top level
configure.ac:1115: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2661: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2678: AC_LINK_IFELSE is expanded from...
m4/libtool.m4:4158: _LT_LINKER_SHLIBS is expanded from...
m4/libtool.m4:5233: _LT_LANG_C_CONFIG is expanded from...
m4/libtool.m4:138: _LT_SETUP is expanded from...
m4/libtool.m4:67: LT_INIT is expanded from...
m4/libtool.m4:102: AC_PROG_LIBTOOL is expanded from...
configure.ac:1115: the top level
configure.ac:1115: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2661: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2678: AC_LINK_IFELSE is expanded from...
m4/libtool.m4:1022: _LT_SYS_MODULE_PATH_AIX is expanded from...
m4/libtool.m4:4158: _LT_LINKER_SHLIBS is expanded from...
m4/libtool.m4:5233: _LT_LANG_C_CONFIG is expanded from...
m4/libtool.m4:138: _LT_SETUP is expanded from...
m4/libtool.m4:67: LT_INIT is expanded from...
m4/libtool.m4:102: AC_PROG_LIBTOOL is expanded from...
configure.ac:1115: the top level
configure.ac:1115: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2661: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2678: AC_LINK_IFELSE is expanded from...
m4/libtool.m4:4158: _LT_LINKER_SHLIBS is expanded from...
m4/libtool.m4:5233: _LT_LANG_C_CONFIG is expanded from...
m4/libtool.m4:138: _LT_SETUP is expanded from...
m4/libtool.m4:67: LT_INIT is expanded from...
m4/libtool.m4:102: AC_PROG_LIBTOOL is expanded from...
configure.ac:1115: the top level
configure.ac:1115: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2661: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2678: AC_LINK_IFELSE is expanded from...
m4/libtool.m4:1022: _LT_SYS_MODULE_PATH_AIX is expanded from...
m4/libtool.m4:4158: _LT_LINKER_SHLIBS is expanded from...
m4/libtool.m4:5233: _LT_LANG_C_CONFIG is expanded from...
m4/libtool.m4:138: _LT_SETUP is expanded from...
m4/libtool.m4:67: LT_INIT is expanded from...
m4/libtool.m4:102: AC_PROG_LIBTOOL is expanded from...
configure.ac:1115: the top level
configure.ac:1115: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2661: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2678: AC_LINK_IFELSE is expanded from...
m4/libtool.m4:4158: _LT_LINKER_SHLIBS is expanded from...
m4/libtool.m4:5233: _LT_LANG_C_CONFIG is expanded from...
m4/libtool.m4:138: _LT_SETUP is expanded from...
m4/libtool.m4:67: LT_INIT is expanded from...
m4/libtool.m4:102: AC_PROG_LIBTOOL is expanded from...
configure.ac:1115: the top level
configure.ac:1115: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2661: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2678: AC_LINK_IFELSE is expanded from...
m4/libtool.m4:1022: _LT_SYS_MODULE_PATH_AIX is expanded from...
m4/libtool.m4:4158: _LT_LINKER_SHLIBS is expanded from...
m4/libtool.m4:5233: _LT_LANG_C_CONFIG is expanded from...
m4/libtool.m4:138: _LT_SETUP is expanded from...
m4/libtool.m4:67: LT_INIT is expanded from...
m4/libtool.m4:102: AC_PROG_LIBTOOL is expanded from...
configure.ac:1115: the top level
configure.ac:1115: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2661: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2678: AC_LINK_IFELSE is expanded from...
m4/libtool.m4:4158: _LT_LINKER_SHLIBS is expanded from...
m4/libtool.m4:5233: _LT_LANG_C_CONFIG is expanded from...
m4/libtool.m4:138: _LT_SETUP is expanded from...
m4/libtool.m4:67: LT_INIT is expanded from...
m4/libtool.m4:102: AC_PROG_LIBTOOL is expanded from...
configure.ac:1115: the top level
configure.ac:326: error: required file 'config/compile' not found
configure.ac:326:   'automake --add-missing' can install 'compile'
src/precision/Makefile.am:3: warning: whitespace following trailing backslash
automake: warning: F77LINK was already defined in condition ENABLE_FORTRAN and !ENABLE_SAAMG, which is included in condition TRUE ...
test/Makefile.am:76: ... 'F77LINK' previously defined here
automake: warning: LINK was already defined in condition !ENABLE_FORTRAN and !ENABLE_SAAMG, which is included in condition TRUE ...
test/Makefile.am:74: ... 'LINK' previously defined here
parallel-tests: error: required file 'config/test-driver' not found
parallel-tests:   'automake --add-missing' can install 'test-driver'
autoreconf: automake failed with exit status: 1

**Comment by anishida** [comment]
Florian,

I have just updated branch develop.
I appreciate it if you could check it.
(test/Makefile.am is not fixed because I could not find any problems.)

Sincerely,
Akira Nishida

**Comment by florianl** [comment]
Hi Akira,

It's mutch better! Well done!

   $ ./reconfigure.sh 
   automake: warning: F77LINK was already defined in condition ENABLE_FORTRAN and !ENABLE_SAAMG, which is included in condition TRUE ...
   test/Makefile.am:82: ... 'F77LINK' previously defined here
   automake: warning: LINK was already defined in condition !ENABLE_FORTRAN and !ENABLE_SAAMG, which is included in condition TRUE ...
   test/Makefile.am:74: ... 'LINK' previously defined here

I added a PR #8 to eliminate another warning.

Kind regards,
 Florian

**Comment by anishida** [comment]
Florian,

Thank you for your request. 
I have merged it. 

Sincerely,
Akira
